version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/watch_man
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=watch_man
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d watch_man"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

